#ifndef	HEARTRATE_SERVICE_H
#define	HEARTRATE_SERVICE_H


#define HEART_RATE_MENSUREMENT		"Heart Rate Measurement"
#define BODY_SENSOR_LOCATION		"Body sensor Location"
#define HEARTRATE_CONTROL_POINT		"Heart Rate Control Point"

enum{
	HEART_RATE_SERVICE,
	
	HEART_RATE_MEASUREMENT_CHAR,
	HEART_RATE_MEASUREMENT_VAL,
	HEART_RATE_MENSUREMENT_CFG,
	HEART_RATE_MENSUREMENT_DESC,
	
	BODY_SENSOR_LOCATION_CHAR,
	BODY_SENSOR_LOCATION_VAL,
	BODY_SENSOR_LOCATION_DESC,
	
	HEARTRATE_CONTROL_POINT_CHAR,
	HEARTRATE_CONTROL_POINT_VAL,
	HEARTRATE_CONTROL_POINT_DESC,
	
	
	HEART_RATE_NB,
};



#endif